### PR TITLE
signatures: fix signature encoding

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-crypto/4)

### CODE REVIEW

**Comment by t-bast** [comment]
Can you explain? It seems that @piedup chose explicitly to use asn1, so why are we reverting to json?

---

Review status: 0 of 2 files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-crypto/4#-:-LFRztaECVCNqI62bgbw:b-jzdvu)*

**Comment by simonvadee** [comment]
sure.

We are still encoding keys and signatures as DER ASN-1 but the signature object itself (containing the public key, the algorithm, the message and the actual signature) cannot be encoded to ASN-1 as only literal types can be encoded. It does not add any value to encode the custom structure to asn1 because the purpose of asn1 is to provide compatibility between crypto systems (whereas our custom Signature type is not meant to be used in other systems).

It seems that I forgot to add tests for the signature encoding and it was not working anyway.

Is it clear enough ?

---

Review status: 0 of 2 files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-crypto/4#-:-LFSCLA3-w1nM9Bk0a39:b3s7h26)*

**Comment by t-bast** [comment]
Got it, makes sense!

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-crypto/4#-:-LFSFCKw9DvrJG2BgALm:b-svvhq2)*

**Comment by t-bast** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-crypto/4#-:-LFSFEL2BsaiVoMjwuft:bnfp4nl)*

**Pull request merged**
