### PR TITLE
keys, signatures, encoding: bootstrap packages

### PR DESCRIPTION
**Pull request by simonvadee**
This repo provides 3 packages:

- signatures: sign and verify messages in a generic way
- keys: generate, parse and encode RSA, ECDSA & ED25519 public & private keys
- encoding: PEM encoding utils

Most of the code comes from @piedup PR in `indigotrace` or already existed in go-`indigocore/cs/signatures`.

I used this package in `go-indigocore` to generate keys and handle signatures (I'm waiting for this PR to be validated to send this other PR) and next, I will update trace (after pierre's PR is merged and maybe after the 0.3.0 indigocore release).

Sorry for the size of the PR ;)

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/crypto/1)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 6 of 19 files at r1.
Review status: 14 of 19 files reviewed at latest revision, 3 unresolved discussions.

---

*[encoding/pem.go, line 24 at r1](https://beta.reviewable.io/reviews/stratumn/crypto/1#-L8XUY0xEQINDKeJ3GTg:-L8XUY0xEQINDKeJ3GTh:bb57d4w) ([raw file](https://github.com/stratumn/crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/encoding/pem.go#L24)):*
> ```Go
> )
> 
> // ErrBadPEMFormat is the error returned when a parsing error occurend when trying to decode a PEM block.
> ```

typo: _occurend_

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/crypto/1)*

**Comment by t-bast** [comment]
Shouldn't we name this repo stratumn/go-crypto? It's more future-proof if we end up requiring a js-crypto as well.

---

Review status: 14 of 19 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/crypto/1#-:-L8Xi4KHEVVfwU0-tXcP:bzensnh)*

**Comment by simonvadee** [comment]
Yes, it'd make more sense indeed, I'll fix that !

---

Review status: 14 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 1 at r1](https://beta.reviewable.io/reviews/stratumn/crypto/1#-L8XSQfb86OIRRWuO6Zd:-L8XkSUN4a1gg4O6oTEt:bkplo5a) ([raw file](https://github.com/stratumn/crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/.gitignore#L1)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why didn't you use the same as https://github.com/stratumn/go-indigocore/blob/master/.gitignore ?
</blockquote></details>

I used this one as an example, but I removed what was useless, do you think something is missing ?

---

*[README.md, line  at r1](https://beta.reviewable.io/reviews/stratumn/crypto/1#-L8XSk3U-tWPK1UMrBe3:-L8XkYp8Dv9xiQeLsdVW:bq0jrp5) ([raw file](https://github.com/stratumn/crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/README.md#L)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Same explanations are missing :(
</blockquote></details>

Oopsies I forgot ! I'm going to fix that asap.

---

*[version.sh, line 32 at r1](https://beta.reviewable.io/reviews/stratumn/crypto/1#-L8XT0fr6ir6tva_XyV4:-L8Xklz819sMK-gLAoHv:b-rmea02) ([raw file](https://github.com/stratumn/crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/version.sh#L32)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

generator section is not necessary
https://github.com/stratumn/indigotrace-api/blob/master/version.sh is simpliest
</blockquote></details>

thank's ! Done.

---

*[encoding/pem.go, line 24 at r1](https://beta.reviewable.io/reviews/stratumn/crypto/1#-L8XUY0xEQINDKeJ3GTg:-L8Xl1Xm37VMGQbLT7B4:b-896fix) ([raw file](https://github.com/stratumn/crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/encoding/pem.go#L24)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

typo: _occurend_
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/crypto/1#-:-L8Xl4_56a3L6B7tQJoB:b-2fkjox)*

**Comment by t-bast** [comment]
Reviewed 19 of 19 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Makefile, line 15 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XibHNADSX3eeqhIgG:-L8XibHPEWuGcURf1GQq:b-i1b0sk) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/Makefile#L15)):*
> ```Makefile
> GO_CMD=go
> GO_LINT_CMD=golint
> KEYBASE_CMD=keybase
> ```

nit: not needed

---

*[keys/ecdsa.go, line 35 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8Xj6Na03S0pk0YaUGI:-L8Xj6Na03S0pk0YaUGJ:botkvi) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/keys/ecdsa.go#L35)):*
> ```Go
> func NewECDSAKeyPair() (crypto.PublicKey, *ecdsa.PrivateKey, error) {
> 	priv, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
> 	return priv.Public(), priv, nil
> ```

If we always return a nil error then we could directly return (crypto.PublicKey, *ecdsa.PrivateKey) which makes people's life easier :)
Otherwise we should not ignore ecdsa.GenerateKey's error.

---

*[keys/keys.go, line 61 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8Xk65ePMmHhcyCVEWs:-L8Xk65ePMmHhcyCVEWt:b8qqyxs) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/keys/keys.go#L61)):*
> ```Go
> }
> 
> func init() {
> ```

I don't think this init is needed, is it? Because if we're using math/rand instead of crypto/rand to generate keys, we're gonna have a baaad time

---

*[keys/keys.go, line 178 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XjyCar9_rTVeg5biF:-L8XjyCcsodhqIuE7_UX:b2mwoaq) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/keys/keys.go#L178)):*
> ```Go
> 
> /*
>  SECRET KEYS' ENCONDING FUNCTION.
> ```

typo: encoding

---

*[signatures/sign.go, line 54 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XkdZZ_DdF19n2Lv8D:-L8XkdZZ_DdF19n2Lv8E:b27t8v4) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/signatures/sign.go#L54)):*
> ```Go
> 			return nil, errors.Errorf("%s private key length must be %d, got %d", algoName[PureED25519], ed25519.PrivateKeySize, len(sk.(ed25519.PrivateKey)))
> 		}
> 		signed = msg
> ```

Why don't we sign the hash for ed25519?

---

*[signatures/sign.go, line 66 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8Xko2mn26wWzuasLcn:-L8Xko2mn26wWzuasLco:b-bcwrxv) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/signatures/sign.go#L66)):*
> ```Go
> 			Algorithm: OIDSignatureECDSAWithSHA256,
> 		}
> 		opts = crypto.Hash(0)
> ```

Why isn't this crypto.SHA256 here?

---

*[signatures/signature.go, line 142 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XlJI7ugeqDT1nSivO:-L8XlJI7ugeqDT1nSivP:bb3y144) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/signatures/signature.go#L142)):*
> ```Go
> 	{x509.MD5WithRSA, OIDSignatureMD5WithRSA, x509.RSA, crypto.MD5},
> 	{x509.SHA1WithRSA, OIDSignatureSHA1WithRSA, x509.RSA, crypto.SHA1},
> 	{x509.SHA1WithRSA, OIDISOSignatureSHA1WithRSA, x509.RSA, crypto.SHA1},
> ```

Why does this one have the same algo than the previous one? Is it expected?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1)*

**Comment by piedup** [comment]
Isn't it worth defining an interface for keypairs defined in `keys/rsa.go`, `keys/ecdsa.go` and `keys.ed25519` with methods such as `Encode`, `Parse` (both for public and private keys) and `Sign` for instance?

Also all keys are encoded in ASN.1 DER + PEM format. Can we only encode to ASN.1 DER and optionally encode to PEM? I don't think we always want PEM encoding. What do you think?

---

Reviewed 6 of 19 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[signatures/signature.go, line 38 at r2](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XmdZ8-KfeOqCaqcuT:-L8XmdZB8Ton0sWhiwhB:b-2ax0zx) ([raw file](https://github.com/stratumn/go-crypto/blob/2497ee319d2e8ad81417fafdbe3d2e8c1947c6f4/signatures/signature.go#L38)):*
> ```Go
> 
> 	// SignaturePEMLabel is the label of a PEM-encoded signed message
> 	SignaturePEMLabel = "MESSAGE"
> ```

Is this a standard encoding for signatures?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-:-L8XjoMB3-bOG2Buh1Mn:bxkd3r1)*

**Comment by alexppxela** [comment]
Or `stratumn/crypto-go` before renaming indigocore suffixed by `-go`

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[.gitignore, line 1 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XSQfb86OIRRWuO6Zd:-L8XmXLN0LW2fZ67n_Ja:b-qd2y2m) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/.gitignore#L1)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

I used this one as an example, but I removed what was useless, do you think something is missing ?
</blockquote></details>

*.DS_Store (for mac users)
*.swp (for stephan)
coverhtml.txt

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-:-L8Xm33wCxX0mRJ1Hs23:b-7xjlkq)*

**Comment by simonvadee** [comment]
(truncated comment)

I'd rather use crypto.PublicKey and crypto.PrivateKey and have Sign and Verify accept the (PEM or ASN1 DER) secret key as argument. I think it makes more sense to work with go standard library's types.

About the PEM vs DER format, my 2 cents: I see DER more as an intermediate format which is used neither for saving keys (unreadable characters) nor for signing/verifying, whereas PEM has to be used every time a user has to manipulate a key. However, RFCs related to key/signature encoding speak in term of DER representation, so maybe it is more "standard" or somehow easier to understand for developers.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-:-L8Y8FQdCL5Vi1-FEdP4:b49hrv3)*

**Comment by t-bast** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[keys/ecdsa.go, line 35 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8Xj6Na03S0pk0YaUGI:-L8YAGaL6dv9VDj7WTxf:b-z6zjfp) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/keys/ecdsa.go#L35)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

I don't know why I ignored it... fixed.
</blockquote></details>

I don't think it's fixed in iteration 3 in this file ;)

---

*[keys/keys.go, line 178 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XjyCar9_rTVeg5biF:-L8YA5Gk1FS5ODxWkuAd:bmld0j9) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/keys/keys.go#L178)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still typo :) should be ENCODING

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1)*

**Comment by simonvadee** [comment]
Review status: 17 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[keys/ecdsa.go, line 35 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8Xj6Na03S0pk0YaUGI:-L8aNtI040GvgEk2p5ls:b-nv9sgd) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/keys/ecdsa.go#L35)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I don't think it's fixed in iteration 3 in this file ;)
</blockquote></details>

there was the same issue in rsa.go, my bad :)

---

*[keys/keys.go, line 178 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XjyCar9_rTVeg5biF:-L8aNKb77eNQnXG1vLfm:bxp25r6) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/keys/keys.go#L178)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Still typo :) should be ENCODING
</blockquote></details>

I wanted to make sure you were following, man you're good.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1)*

**Comment by t-bast** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[keys/ecdsa.go, line 35 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8Xj6Na03S0pk0YaUGI:-L8aPtce--Ndh3Qay3hS:b1syi6w) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/keys/ecdsa.go#L35)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

there was the same issue in rsa.go, my bad :)
</blockquote></details>

Not sure, but isn't there a risk of priv being nil in case of error which would result in a null ref when trying to get priv.Public()?

---

*[keys/keys.go, line 178 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XjyCar9_rTVeg5biF:-L8aQ3AkE5OiugaET38u:b32vir) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/keys/keys.go#L178)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

I wanted to make sure you were following, man you're good.
</blockquote></details>

;)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1)*

**Comment by simonvadee** [comment]
Review status: 17 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[keys/ecdsa.go, line 35 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8Xj6Na03S0pk0YaUGI:-L8aYx9w2xldWnq1eyb8:b-no4i10) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/keys/ecdsa.go#L35)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Not sure, but isn't there a risk of priv being nil in case of error which would result in a null ref when trying to get priv.Public()?
</blockquote></details>

it is very possible indeed. Fixed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-:-L8aZ_pp7O7wXgfrLnSD:bnfp4nl)*

**Comment by bejito** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 1 at r1](https://reviewable.io:443/reviews/stratumn/go-crypto/1#-L8XSQfb86OIRRWuO6Zd:-L8bUn7153MF53YqCl30:b-dcs0b3) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/.gitignore#L1)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`*~` also for vi users. (These should be in our global .gitignore anyway)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-crypto/1)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[.gitignore, line 1 at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XSQfb86OIRRWuO6Zd:-L8bvkz0DarZOyu7U-GL:bwntuvq) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/.gitignore#L1)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

`*~` also for vi users. (These should be in our global .gitignore anyway)
</blockquote></details>

`*~` is for emacs users. But I think I was the last specimen who used it in the team.
But yes, you're true, specific ignore shold be in our own .gitignore

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 11 of 19 files at r1, 2 of 2 files at r2, 3 of 5 files at r3, 1 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-:-L8fRWqW1wYu2LWj9el8:bnfp4nl)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-:-L8gN4s97y2KlVo2Jh_M:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1)*

**Comment by simonvadee** [comment]
Review status: 12 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line  at r1](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8XSk3U-tWPK1UMrBe3:-L8hCVIP5BcboEdwuVsr:bnl1os4) ([raw file](https://github.com/stratumn/go-crypto/blob/123ce80647301ba72730ad5f8d14ae2d84bf6f71/README.md#L)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

The readme is empty?
</blockquote></details>

I added a basic one, I'll improve it later

---

*[keys/keys.go, line 142 at r7](https://beta.reviewable.io/reviews/stratumn/go-crypto/1#-L8gttE-7B8rhDPdyw-C:-L8h2pjH16wHlMheENty:b-tf4m94) ([raw file](https://github.com/stratumn/go-crypto/blob/30f9a4bc051fb494e9ee6c737e6ca248b8114127/keys/keys.go#L142)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

it's weird that we're mixing pointer and values in the cases
</blockquote></details>

`ed25519.GenerateKey()` does not return a pointer, as opposed to the others `.GenerateKey()`. But I agree that it looks inconsistent, I replaced it with pointers everywhere.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-crypto/1)*

**Comment by such** [comment]
:lgtm:

---

Review status: 12 of 19 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-crypto/1#-:-L8hGX_sst5nbCOznGuE:bnfp4nl)*

**Pull request merged**
